### ISSUE TITLE
[QUESTION] Search Custom Property Columns

### ISSUE THREAD

**Issue by cihangll** [fingers10/JqueryDataTablesServerSide#18]
Hi Abdul,
 
How can i search custom property columns?

#### For example; 

I have an enum in the entity model like this.
```csharp
public enum ItemType : short {
	[Display(Name = "Item Card")]
	InventoryCard = 0,
	[Display(Name = "Service Card")]
	ServiceCard = 4
}
```
```csharp
[DisplayName("Item Type")]
[Sortable]
[SearchableString]
public string ItemType { get; set; }
```
```csharp
CreateMap<ItemTransfer, ItemCardDataTableModel>()
     .ForMember(dest => dest.ItemType, opt => opt.MapFrom(src => src.ItemType.GetDisplayName()))......
```

I want to search display name on the datatable but i am getting error like this;
![image](https://user-images.githubusercontent.com/6229029/66486031-87817f80-eab2-11e9-9aed-8658a44357bf.png)

Because UI property type is string and the entity property type is short. 

#### Other Example;

I have a name and surname property in the entity model.
I want to show Name + Surname => **NameSurname** column on the UI. How can i search this column? 

Thanks.

**Comment by chrisxh** [comment]
Hi @cihangll,
Depending on the arguments that you're passing to `SearchOptionsProcessor.Apply()`,  I think the server-side part of JqueryDataTables**ServerSide** may be getting in the way of what you want.  Are you passing an `IQueryable<ItemTransfer>`?   
If so, the `SearchOptionsProcessor.Apply` method will be querying (searching) against the source `ItemTransfer` type, not the projected `ItemCardDataTableModel` type.  

When the incoming datatables query parameters (`JqueryDataTablesParameters`) are saying, _"please search for the string 'Item Card' in the column named 'ItemType'"_, JQDT will produce a server-side expression like `ItemTransfer.ItemType.Contains("Item Card")`.

Because `ItemTransfer.ItemType` cannot be convinced to behave like a string, the exception appears.

In order to search by string on the `ItemCardDataTableModel.ItemType`, you need to pass an argument of type `IQueryable<ItemCardDataTableModel>` to  `SearchOptionsProcessor.Apply()`.    This is also how you can achieve a search against a `NameSurname` column.

**Comment by fingers10** [comment]
Hi @chrisxh,

Thanks for the explanation.

Hi @cihangll,

Right now the package doest support enum type/custom type. I had a long thought of implementing this. I'll try to see if I can find a way to make this happen with attributes.

Thanks,
Abdul

**Comment by fingers10** [comment]
@cihangll, look at this [enum filtering issue](https://github.com/aspnet/EntityFrameworkCore/issues/11127). Looks like if you configure your entity properly in efcore then enum filtering has to work. I'll try from my end and get back to you.

**Comment by fingers10** [comment]
@cihangll If your using ef core why don't you try [value converters](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) for `enum` properties? I'm focusing on asp.net core 3.0 upgrade. I'll try a sample after that.

**Comment by cihangll** [comment]
@fingers10 Thank you for that. I'll try value converters for enum properties.

**Comment by fingers10** [comment]
@cihangll , I tried with value converters. Looks like I need to define an extra attribute like `[SearchableEnum(typeof(YourEnum))]` for that to work. I'll add this in the next release.

**Comment by fingers10** [comment]
@cihangll but `[SearchableEnum(typeof(YourEnum))]` will only allow `eq` search.  when I try `co` `Enum.TryParse<TEnum>` throws exception. This has this limitation. But for `eq` case you enter the enum value with or without space `Enum.TryParse<TEnum>` will succeed.

**Comment by cihangll** [comment]
@fingers10 This is awesome. Thank you for this enhancement.
