### ISSUE TITLE
How to Hide unwanted model fields in the grid?

### ISSUE THREAD

**Issue by HunainD** [fingers10/JqueryDataTablesServerSide#24]
Hi Abdul Rahman, 
Great job its really a nice article. I am using jquery datatable in my project but the problem is i dont want to show some of my model fields in my grid how can i achieve this. i tried using the visible property of grid column but did't work.

secondly my param for LoadData is always null and i am not able to solve this problem can you help me regarding this? for this i have made some tests and i came to know that it is null because the "Order" property of "JqueryDataTablesParameters" is not binding to the posted data. i did this by creating my own test paramerter class and included all the fields other than "Order" and ı was able to see the posted data. 
Am i doing somthing wrong with order configuration. 
My model class is 
public class VanInformationViewModel : BaseViewModel
    {
        [SearchableString]
        [Sortable(Default = true)]
        [Display(Name ="Number Plate")]
        public string NumberPlate { get; set; }
        [SearchableString]
        [Sortable]
        [Display(Name = "Driver")]
        public string DriverName { get; set; }
        [SearchableString]
        [Sortable]
        [Display(Name = "Helper")]
        public string HelperName { get; set; }

        [Display(Name = "Driver Contact")]
        public string DriverContactNumber { get; set; }
        [Display(Name = "Helper Contact")]
        public string HelperContactNumber { get; set; }
    }
Id and CreatedDate properties are in my base class and these are the fields i dont want to show on grid. 
Regards
Hunain

**Comment by fingers10** [comment]
Hey @HunainD ,

1. >i dont want to show some of my model fields in my grid how can i achieve this

Right now I recommend to have a view model with only the fields that you need to show in UI. Hence you can remove the inheritance from `BaseViewModel` or create a separate view model class that holds only the properties that you wish to show in UI. Or on the flip side if you don't want to make any changes to your view model, then the simple solution is to hide the column by configuring the column definition from table initialization script like shown below:

```js
{
    data: "Id",
    name: "eq",
    visible: false,
    searchable: false,
    orderable: false
},
{
    data: "CreatedDate",
    name: "eq",
    visible: false,
    searchable: false,
    orderable: false
},
```

2. >my param for LoadData is always null because the "Order" property of "JqueryDataTablesParameters" is not binding to the posted data. i did this by creating my own test paramerter class and included all the fields other than "Order".  i did this by creating my own test paramerter class.

First why did you create your own class when you have `JqueryDataTablesParameters` class that do the work out of the box? I recommend using `JqueryDataTablesParameters` which comes with the package. Anyways for your question here is the solution,

The `DTOrder` class has enum property `DTOrderDir` in it and that's why your model binding fails.
```c#
public class DTOrder
{
    public DTOrder();

    public int Column { get; set; }
    public DTOrderDir Dir { get; set; }
}
```
make sure you configure your json options as shown in [docs](https://github.com/fingers10/JqueryDataTablesServerSide#startupcs) 

P.S Please add star to my repo if you like this project. Feel free to get back if you face any issues.

Cheers,
Abdul Rahman

**Comment by HunainD** [comment]
Thanks Abdul Rahaman it worked for me, for hiding columns i had to add the columns to hide at the end of the initialization script.
